### ISSUE TITLE
Missing `astyle` style

### ISSUE THREAD

**Issue by Peque** [micromouseonline/micromouse-maze#3]
When compiling the project, `astyle` is executed. Could a configuration file with the style options be missing?

When I execute it in my computer, all source code files get modified, so I guess the default in my system/version is different from yours.

Maybe adding a configuration file or a `--style=xxx` option to the command would help.

Note that the `astyle` command is both in `CMakeLists.txt` and `tests/test_suite/CMakeLists.txt`. Is that intentional?

**Comment by micromouseonline** [comment]
Thank you for taking the time to look at this and try to build it.

I confess I do not know how to handle pull requests on github. I must look into that. I will reject or delete your pull request until I can find a better way to deal with it.

Meantime, I have had a look through your suggestions and gone back to the code to implement them and a few other changes. I will reject or delete your pull request until I can find a better way to deal with it.

I think I have caught all the issues you mention. Let me know if there are any other problems. I make no claims about the main.cpp code quality. It is hacked together to let me answer a specific question.

There is a brief readme update that tells what the libmaze_run target does.

Mostly, the project is, like o many on github, just held there as an off-site backup. If you find it useful let me know. The libMaze library is exactly what goes into my micromouse since it is included as a subtree in the mouse code.

Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
@micromouseonline Thanks to you for sharing all this and for the fixes! It seems to work fine now. :blush:

For now our mouse still only has a simple flood fill implemented, with no path finding and not very good command processing implementation:

https://www.youtube.com/watch?v=_BIif0DPo3k

But we will definitely have a look at your `libMaze` code soonish! (currently we are in the process of changing some hardware and adding a gyroscope, which is still mising in our design...). :joy:

**Comment by micromouseonline** [comment]
You can do remarkably well without a gyro.

Do you have anything online to look at?

Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
Thanks! We miss the gyro when the tires get dusty and start to drift. As long as there is no drift, turns are very precise just with the encoders.

Our project is all online. Did not tell you but we are [Miguel](https://github.com/Peque/) and [Clara](https://github.com/cua-cua). You published our mouse in your website a couple of months ago:

- Source Code: https://github.com/Theseus
- Schematic/PCB: https://upverter.com/Peque/3d82ffa66d538f81/Theseus/

Did not change much since then, but we are starting to work again with this project and prepare for the Portuguese contest. Hope to see you there! :blush:

**Comment by micromouseonline** [comment]
Of course!

I forgot - sorry.

In the next day or two I will put up my maze file collection and a tool for converting maze files.

Peter Harrison
peter.harrison@helicron.net

**Comment by micromouseonline** [comment]
Maze files are up:

https://github.com/micromouseonline/micromouse_maze_tool

Looking forward to Portugal.

Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
Awesome, thanks for sharing! :blush:
